[package]
name = "forkpress"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.5"
flate2 = "1.1"
libc = "0.2"
num_cpus = "1.16"
tar = "0.4"
zip = { version = "2.4", default-features = false, features = ["deflate"] }

[build-dependencies]
anyhow = "1.0"
flate2 = "1.1"
tar = "0.4"
walkdir = "2.5"
